version: '3'
services:

  myst-provider:
    build:
      context: ../..
      dockerfile: bin/docker/alpine/Dockerfile
    depends_on:
      - broker
      - mysterium-api
      - ipify
      - transactor
      - accountant
    cap_add:
      - NET_ADMIN
    expose:
      - 1194
      - 4050
    volumes:
      - ../../e2e/myst-provider/keystore:/var/lib/mysterium-node/keystore
    command: >
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual
      --location.country=e2e-land
      --experiment-identity-check
      --localnet
      --broker-address=broker
      --api.address=http://mysterium-api:8001/v1
      --ether.client.rpc=ws://ganache:8545
      --transactor.registry-address=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --transactor.channel-implementation=0x599d43715DF3070f83355D9D90AE62c159E62A75
      --accountant.accountant-id=0xf2e2c77D2e7207d8341106E6EfA469d1940FD0d8
      --accountant.address=http://accountant:8889/api/v1
      --transactor.address=http://transactor:8888/api/v1
      --ether.contract.payments=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --keystore.lightweight
      service openvpn,noop,wireguard
      --agreed-terms-and-conditions
      --identity=0xd1a23227bd5ad77f36ba62badcb78a410a1db6c5
      --identity.passphrase=localprovider
      --openvpn.port=3000

  myst-consumer:
    build:
      context: ../..
      dockerfile: bin/docker/alpine/Dockerfile
    depends_on:
      - broker
      - mysterium-api
      - ipify
      - transactor
      - accountant
    cap_add:
      - NET_ADMIN
    expose:
      - 4050
    command: >
      --transactor.registry-address=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --accountant.accountant-id=0xf2e2c77D2e7207d8341106E6EfA469d1940FD0d8
      --accountant.address=http://accountant:8889/api/v1
      --transactor.address=http://transactor:8888/api/v1
      --transactor.channel-implementation=0x599d43715DF3070f83355D9D90AE62c159E62A75
      --ether.contract.payments=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --ip-detector=http://ipify:3000/?format=json
      --experiment-identity-check
      --localnet
      --api.address=http://mysterium-api:8001/v1
      --ether.client.rpc=ws://ganache:8545
      --keystore.lightweight
      --firewall.killSwitch.always
      daemon

  #'external' IP detection
  ipify:
    image: owlab/ipify
    expose:
    - 3000
